import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="p-4 bg-green-700 text-white">
          <nav className="flex gap-6">
            <a href="/" className="font-bold">Masjid</a>
            <a href="/events">Events</a>
            <a href="/videos">Videos</a>
            <a href="/donations">Donations</a>
            <a href="/expenses">Expenses</a>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
